source 'https://rubygems.org'
ruby '2.7.6'
gem 'letter_opener'
gem 'nokogiri'
gem 'rails', '>= 6.1.6.1'
gem 'rake'
gem 'json'
gem 'sprockets-rails'
gem 'sprockets-helpers'
gem 'mini_racer', '0.4.0'
gem 'select2-rails'
gem 'jquery-ui-rails'
gem 'mysql2'
gem 'aasm'
gem 'declarative_authorization'
gem 'delayed_job_active_record'
gem 'newrelic_rpm'

group :development do
  gem 'i18n-tasks'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'xray-rails'
  gem 'web-console', '~> 4.2'
  gem 'capistrano'
  gem 'rvm-capistrano', require: false
  gem 'letter_opener'
  gem 'overcommit'
  gem 'rack-mini-profiler'
end

group :development, :test do
  gem 'ruby-prof'
  gem 'memory_profiler'
  gem 'flamegraph'
  gem 'roo'
  gem 'parallel_tests'
  gem 'rb-readline'
  gem 'pry'
  gem 'pry-byebug'
  gem 'license_finder'
  gem 'test-prof'
  gem 'fasterer'
  gem 'bullet'
end

group :test do
  gem 'timecop'
  gem 'rspec-rails'
  gem 'rspec-mocks'
  gem 'rspec-activemodel-mocks'
  gem 'rspec-its'
  gem 'rspec-collection_matchers'
  gem 'rspec-benchmark'
  gem 'rails-controller-testing' 
  gem 'capybara'
  gem 'poltergeist'
  gem 'capybara-screenshot'
  gem 'capybara-select2'
  gem 'webmock'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'rubocop-rspec', '>=2.0.0.pre', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-ast', require: false
  gem 'rubocop-rake', require: false
  gem 'reek', '>= 5.4'
end

gem 'acts_as_list'
gem 'acts_as_tree'
gem 'deep_cloneable'
gem 'simple_form'
gem 'cancancan'
gem 'carrierwave'
gem 'wicked_pdf'
gem 'nested_form'
gem 'memoist'
gem 'truncate_html'
gem 'puma'
gem 'exception_notification'
gem 'iconv'
gem 'acts-as-taggable-on'
gem 'devise'
gem 'uk_postcode'
gem 'ckeditor', '~>4.3.0'
gem 'redis'
gem 'paper_trail'
gem 'api-pagination'
gem 'pagy'
gem 'activemodel-serializers-xml'
gem 'activerecord-import'
gem 'webpacker', '~> 5'
gem 'searchkick'
